#!/bin/sh

MINDUSTRY_ADDRESS=localhost
MINDUSTRY_PORT=6859
LISTEN_ADDRESS=127.0.0.1
LISTEN_PORT=8990

websocketd -maxforks=1 -port $LISTEN_PORT -address=$LISTEN_ADDRESS -- nc $MINDUSTRY_ADDRESS $MINDUSTRY_PORT
